/**
 * Represents a minimal activity record from Strava
 */
export interface ActivityStub {
  /** Strava activity ID */
  id: string;
  /** Activity name/title */
  name: string;
  /** ISO 8601 date string */
  startDate: string;
  /** Encoded polyline string for map rendering */
  polyline: string;
  /** Distance in meters */
  distance: number;
}

/**
 * Payload for insight requests and responses
 */
export interface InsightPayload {
  /** The user's question about their activities */
  question: string;
  /** Natural language answer generated by the MCP server */
  answer: string;
  /** List of activities that support the answer */
  supportingActivities: ActivityStub[];
}

/**
 * Error response structure
 */
export interface ErrorResponse {
  /** HTTP status code */
  status: number;
  /** Error message */
  message: string;
  /** Optional error details */
  details?: unknown;
}
